#!/usr/bin/env bash
# Prepare a project for the Hydra-Pod workflow.
# usage: init-project.sh [project-dir]   (default: current directory)
#
# Creates the ticket layout and installs the verified reviewer agent, the dispatch
# watchdog and a workers.md draft. Never overwrites an existing file: an existing
# opencode.json without a `reviewer` agent is reported, not modified.
set -euo pipefail
here=$(cd "$(dirname "$0")/.." && pwd)
tpl=$here/templates/project
dest=$(cd "${1:-.}" && pwd)

say() { printf '%-8s %s\n' "$1" "$2"; }

[ -d "$dest/.git" ] || say warn "$dest is not a git repository (acceptance commits need git)"

for d in open doing done blocked dropped; do
  mkdir -p "$dest/_tickets/$d"
  [ -e "$dest/_tickets/$d/.gitkeep" ] || touch "$dest/_tickets/$d/.gitkeep"
done
mkdir -p "$dest/_receipts"; [ -e "$dest/_receipts/.gitkeep" ] || touch "$dest/_receipts/.gitkeep"
say ok "_tickets/{open,doing,done,blocked,dropped} and _receipts/"

copy_new() {  # src rel-dest
  if [ -e "$dest/$2" ]; then say skip "$2 exists (left unchanged)"; else cp "$1" "$dest/$2"; say added "$2"; fi
}
copy_new "$tpl/_tickets/run-watchdog.sh" _tickets/run-watchdog.sh
chmod +x "$dest/_tickets/run-watchdog.sh"
copy_new "$tpl/_tickets/workers.md.template" _tickets/workers.md
copy_new "$tpl/_tickets/TICKET.template.md" _tickets/TICKET.template.md
# _tickets/STATE.md is regenerated by `hydra-pod-dispatch status`; keep it out of git.
if ! grep -qx '_tickets/STATE.md' "$dest/.gitignore" 2>/dev/null; then
  echo '_tickets/STATE.md' >> "$dest/.gitignore"; say added ".gitignore entry _tickets/STATE.md"
fi

if [ -e "$dest/opencode.json" ]; then
  if python3 -c 'import json,sys; sys.exit(0 if "reviewer" in json.load(open(sys.argv[1])).get("agent",{}) else 1)' "$dest/opencode.json" 2>/dev/null; then
    say skip "opencode.json already defines agent 'reviewer'"
  else
    say ACTION "opencode.json exists without a 'reviewer' agent: merge the \"agent\" block from $tpl/opencode.json by hand"
  fi
else
  cp "$tpl/opencode.json" "$dest/opencode.json"; say added "opencode.json (reviewer agent)"
fi

echo
echo "providers (no quota used):"
"$here/bin/hydra-pod-connect" status </dev/null 2>&1 | sed 's/^/  /' || true

cat <<EOF

next:
  1. Adjust the reviewer bash allowlist in opencode.json to this project's test command
     (the template allows only read-only git and 'python3 -B -m unittest*').
  2. Any provider not Connected: hydra-pod-connect connect <provider>   (browser login)
  3. In Claude Code, from $dest:  /hydra-pod <task>
     The skill asks the first-use questions and runs the trials, then completes _tickets/workers.md.
EOF
